std_msgs/Header header

float32 measure_value

uint8 useing_type  
uint8 type_unknow=0             
uint8 type_calibrat_data=1            
uint8 type_save_data=2
uint8 type_check_data=3

uint8 type  
uint8 type_UNKNOW=0             #0-未知
uint8 type_UP_DOWN=1            #插齿升降
uint8 type_FORWORD_BACKWORD=2   #门架伸缩
uint8 type_RIGHT_LEFT=3         #插齿左右
uint8 type_PITCH=4              #插齿俯仰
uint8 type_ROLL=5              #横滚
uint8 type_YAW=6              #航向