string scheduleip                       # 调度服务器地址
int32  scheduleport
string local_scheduleip                 # 调度对应的本机地址
int32  local_scheduleport
string map_server_ip                    # 地图服务器地址
int32  map_server_port
string robot_ip                         # 机器人地址
int32  robot_port
string interfaceip                      # 接口板地址
int32  interfaceport
string local_interfaceip                # 接口板对应的本机地址
int32  local_interfaceport
string wifi_ip                          # wifi模块地址
int32  wifi_port
string community                        #
string HTTP_POST                        #
string HTTP_POST_APPLY                  # 
string HTTP_POST_FINISH                 #
string HTTP_POST_RESUME                 #
string HTTP_POST_ACTION                 #
string HTTP_POST_ERROR                  # 
string HTTP_GET                         #
string HTTP_GET_MAP                     #
string HTTP_CHARGE_REQ                  # 充电请求
string HTTP_ONEKEYRESET                 # 
string HTTP_POST_REPORT                 #