std_msgs/Header header
uint8 SOUND_TYPE
uint8   SOUND_SELECT_CLOSE = 0
uint8   SOUND_SELECT_RUN = 1              # 运行音乐
uint8   SOUND_SELECT_BACK = 2             # 倒车请注意
uint8   SOUND_SELECT_ALARM = 3            # 机器人故障
uint8   SOUND_SELECT_MANAUL_SHUTDOWN = 4  # 系统关机请将车人工移至起始位置重新上电
uint8   SOUND_SELECT_START_COMPLETE = 5   # 系统完成启动
uint8   SOUND_SELECT_CHECK_COMPLETE = 6   # 系统完成自检
uint8   SOUND_SELECT_STARTING = 7         # 系统正在启动
uint8   SOUND_SELECT_CHECKING = 8         # 系统正在自检
uint8   SOUND_SELECT_ROTATION_RIGHT = 9   #右转请注意
uint8   SOUND_SELECT_AUTOMIC = 10         # 自动模式
uint8   SOUND_SELECT_ROTATION_LEFT = 11   # 左转请注意
uint8   SOUND_SELECT_ARRIVED = 12          # 到达指定位置
uint8   SOUND_SELECT_GO_HOME = 13         # 注意车将回起始位
uint8   SOUND_SELECT_MANAUL = 14          # 手动模式
uint8   SOUND_SELECT_NUMBER_END = 15